Update development-overview.md
languagetool-org/languagetool-org.github.io pull request #10
Opened 2023-01-12 12:01 UTC by LucieSteib

Adding a mention to the runtime exception error in section Variables.

2023-01-12 12:01 UTC, LucieSteib commented
@jaumeortola as discussed on slack, here's a mention of the error and a link to the page with more detailed info.

2023-09-14 10:37 UTC, maphjo requested changes

2023-09-14 10:37 UTC, maphjo commented on development-overview.md
> +It should be noted that the tocken matching the pattern has to match the pattern in the suggestion. If the expression is not the same a runtime exception error can occur (see more information on runt
```suggestion
It should be noted that the token matching the pattern has to match the pattern in the suggestion. If the expression is not the same a runtime exception error can occur (see more information on runtime exception errors [here](https://languagetooler.atlassian.net/wiki/spaces/DEV/pages/1959297044/XML+Rules+Possible+Error+Messages+How+to+solve).
```

2023-09-14 10:45 UTC, maphjo approved these changes

2023-09-14 10:46 UTC, merged